apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: devops-project 

spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: nginx
  template: 
    metadata:
      labels: 
        app: nginx
          
    spec:
      containers: 
        - name: ngix 
          image: nginx:latest 
          ports: 
            - containerPort: 80   
