name: CD Pipeline

on: 
  push: 
    branches: 
      - main 

jobs: 
  deploy: 
    runs-on: self-hosted
  
    steps: 

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{secrets.KUBECONFIG}}" > $HOME/.kube/config

      - name: Ensure monitoring namespace exists
        run: |
          kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        run: |
          kubectl delete job flask-db-init -n flask-app --ignore-not-found=true
          
          sleep 5

          kubectl apply -f k8s/

          kubectl set image deployment/flask-deployment \
          flask-container=techinnovihamid/flask-um-app:${{ github.sha }} \
          -n flask-app

          kubectl rollout status deployment/flask-deployment -n flask-app

           
