name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy-scan:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t flask-app:ci .

    - name: Run Trivy Scan
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: flask-app:ci
        format: table
        exit-code: 1
        ignore-unfixed: true
        severity: CRITICAL,HIGH
